import { type TileType } from "../types.js";

const MAP_LVL_1: TileType[][] = [
  ["TL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "TR", "TL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "TR",],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "PP", "WV", "WV", "PP", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV",],
  ["WV", "FD", "TL", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "TR", "FD", "WV",],
  ["WV", "FD", "WV", "ES", "ES", "WV", "FD", "WV", "ES", "ES", "ES", "WV", "FD", "WV", "WV", "FD", "WV", "ES", "ES", "ES", "WV", "FD", "WV", "ES", "ES", "WV", "FD", "WV",],
  ["WV", "FD", "BL", "WH", "WH", "BR", "FD", "BL", "WH", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "WH", "BR", "FD", "BL", "WH", "WH", "BR", "FD", "WV",],
  ["WV", "PP", "FD", "FD", "FD", "BY", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "PP", "WV",],
  ["WV", "FD", "TL", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "WH", "WH", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "TR", "FD", "WV",],
  ["WV", "CE", "BL", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "TR", "TL", "WH", "WH", "BR", "FD", "WV", "WV", "IY", "BL", "WH", "WH", "BR", "FD", "WV",],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "WV",],
  ["BL", "WH", "WH", "WH", "WH", "TR", "FD", "WV", "BL", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "BR", "WV", "FD", "TL", "WH", "WH", "WH", "WH", "BR",],
  ["ES", "ES", "ES", "ES", "ES", "WV", "FD", "WV", "TL", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "TR", "WV", "FD", "WV", "ES", "ES", "ES", "ES", "ES",],
  ["ES", "ES", "ES", "ES", "ES", "WV", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "GL", "GL", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "WV", "ES", "ES", "ES", "ES", "ES",],
  ["ES", "ES", "ES", "ES", "ES", "WV", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "ES", "ES", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "WV", "ES", "ES", "ES", "ES", "ES",],
  ["ES", "WH", "WH", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "WV", "ES", "ES", "ES", "ES", "ES", "ES", "WV", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "WH", "WH", "ES",],
  ["TP", "FD", "FD", "FD", "FD", "FD", "PP", "FD", "FD", "FD", "WV", "ES", "ES", "ES", "ES", "ES", "ES", "WV", "FD", "FD", "FD", "PP", "FD", "FD", "PY", "FD", "FD", "TP",],
  ["ES", "WH", "WH", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "WV", "ES", "ES", "ES", "ES", "ES", "ES", "WV", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "WH", "WH", "ES",],
  ["ES", "ES", "ES", "ES", "ES", "WV", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "WV", "ES", "ES", "ES", "ES", "ES",],
  ["ES", "ES", "ES", "ES", "ES", "WV", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "WV", "ES", "ES", "ES", "ES", "ES",],
  ["ES", "ES", "ES", "ES", "ES", "WV", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "WH", "WH", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "WV", "ES", "ES", "ES", "ES", "ES",],
  ["TL", "WH", "WH", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "TR", "TL", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "WH", "WH", "TR",],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV",],
  ["WV", "FD", "TL", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "TR", "FD", "WV",],
  ["WV", "FD", "BL", "WH", "TR", "WV", "FD", "BL", "WH", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "WH", "BR", "FD", "WV", "TL", "WH", "BR", "FD", "WV",],
  ["WV", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "ES", "PM", "ES", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "WV",],
  ["BL", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "WH", "WH", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "BR",],
  ["TL", "WH", "BR", "FD", "BL", "BR", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "TR", "TL", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "BL", "BR", "FD", "BL", "WH", "TR",],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "PP", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "PP", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "WV",],
  ["WV", "FD", "TL", "WH", "WH", "WH", "WH", "BR", "BL", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "BR", "BL", "WH", "WH", "WH", "WH", "TR", "FD", "WV",],
  ["WV", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "WV",],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV",],
  ["BL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "BR",],
];

export { MAP_LVL_1 };
