import type { TileType } from "../logic/grid/GridMatrix.js";

export const CFG_GRID_0: TileType[][] = [
  ["ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES"],
  ["ES", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "ES"],
  ["ES", "WL", "PP", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "WL", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "PP", "WL", "ES"],
  ["ES", "WL", "DT", "WL", "WL", "WL", "DT", "WL", "WL", "WL", "WL", "DT", "WL", "DT", "WL", "WL", "WL", "WL", "DT", "WL", "WL", "WL", "DT", "WL", "ES"],
  ["ES", "WL", "DT", "WL", "WL", "WL", "DT", "WL", "WL", "WL", "WL", "DT", "WL", "DT", "WL", "WL", "WL", "WL", "DT", "WL", "WL", "WL", "DT", "WL", "ES"],
  ["ES", "WL", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "WL", "ES"],
  ["ES", "WL", "DT", "WL", "WL", "WL", "DT", "WL", "DT", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "DT", "WL", "DT", "WL", "WL", "WL", "DT", "WL", "ES"],
  ["ES", "WL", "DT", "DT", "DT", "DT", "DT", "WL", "DT", "DT", "DT", "DT", "WL", "DT", "DT", "DT", "DT", "WL", "DT", "DT", "DT", "DT", "DT", "WL", "ES"],
  ["ES", "WL", "WL", "WL", "WL", "WL", "DT", "WL", "WL", "WL", "WL", "DT", "WL", "DT", "WL", "WL", "WL", "WL", "DT", "WL", "WL", "WL", "WL", "WL", "ES"],
  ["ES", "ES", "ES", "ES", "ES", "WL", "DT", "WL", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "WL", "DT", "WL", "ES", "ES", "ES", "ES", "ES"],
  ["ES", "ES", "ES", "ES", "ES", "WL", "DT", "WL", "DT", "WL", "WL", "LE", "LE", "LE", "WL", "WL", "DT", "WL", "DT", "WL", "ES", "ES", "ES", "ES", "ES"],
  ["ES", "WL", "WL", "WL", "WL", "WL", "DT", "WL", "DT", "WL", "LT", "LT", "LT", "LT", "LT", "WL", "DT", "WL", "DT", "WL", "WL", "WL", "WL", "WL", "ES"],
  ["ES", "0A", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "WL", "BY", "IY", "LT", "PY", "CE", "WL", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "0A", "ES"],
  ["ES", "WL", "WL", "WL", "WL", "WL", "DT", "WL", "DT", "WL", "LT", "LT", "LT", "LT", "LT", "WL", "DT", "WL", "DT", "WL", "WL", "WL", "WL", "WL", "ES"],
  ["ES", "ES", "ES", "ES", "ES", "WL", "DT", "WL", "DT", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "DT", "WL", "DT", "WL", "ES", "ES", "ES", "ES", "ES"],
  ["ES", "ES", "ES", "ES", "ES", "WL", "DT", "WL", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "WL", "DT", "WL", "ES", "ES", "ES", "ES", "ES"],
  ["ES", "WL", "WL", "WL", "WL", "WL", "DT", "WL", "DT", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "DT", "WL", "DT", "WL", "WL", "WL", "WL", "WL", "ES"],
  ["ES", "WL", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "WL", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "WL", "ES"],
  ["ES", "WL", "DT", "WL", "WL", "WL", "DT", "WL", "WL", "WL", "WL", "DT", "WL", "DT", "WL", "WL", "WL", "WL", "DT", "WL", "WL", "WL", "DT", "WL", "ES"],
  ["ES", "WL", "DT", "DT", "DT", "WL", "DT", "DT", "DT", "DT", "DT", "DT", "PM", "DT", "DT", "DT", "DT", "DT", "DT", "WL", "DT", "DT", "DT", "WL", "ES"],
  ["ES", "WL", "WL", "WL", "DT", "WL", "DT", "WL", "DT", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "DT", "WL", "DT", "WL", "DT", "WL", "WL", "WL", "ES"],
  ["ES", "WL", "DT", "DT", "DT", "DT", "DT", "WL", "DT", "DT", "DT", "DT", "WL", "DT", "DT", "DT", "DT", "WL", "DT", "DT", "DT", "DT", "DT", "WL", "ES"],
  ["ES", "WL", "DT", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "DT", "WL", "DT", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "DT", "WL", "ES"],
  ["ES", "WL", "PP", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "DT", "PP", "WL", "ES"],
  ["ES", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "WL", "ES"],
  ["ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES"],
];